/aruco_node:
  ros__parameters:
    marker_size: 0.095 # 0.16 # 0.202  # 14 / 9
    aruco_dictionary_id: DICT_4X4_1000 # DICT_5X5_50
    image_topic: /camera_data/compressed
    camera_info_topic: /camera_data/camera_info
    display_image: true
